In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4])
print(arr)
arr1=arr+3
print(arr1)

[1 2 3 4]
[4 5 6 7]


In [5]:
arr1=np.array([1,2,3,4])
print(arr1)
arr2=np.array([[10],[20],[30],[40]])
print(arr2)
arr1+arr2
print(arr)

[1 2 3 4]
[[10]
 [20]
 [30]
 [40]]
[1 2 3 4]


In [6]:
arr1=np.arange(1,9)
print(arr1)
arr2=np.arange(10,18).reshape(2,4)
print(arr2)
arr=arr1+arr2
print(arr)

[1 2 3 4 5 6 7 8]
[[10 11 12 13]
 [14 15 16 17]]


ValueError: operands could not be broadcast together with shapes (8,) (2,4) 

In [7]:
arr1=np.arange(1,9)
print(arr1)
arr2=np.arange(10,18).reshape(8,1)
print(arr2)
arr=arr1+arr2
print(arr)

[1 2 3 4 5 6 7 8]
[[10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]]
[[11 12 13 14 15 16 17 18]
 [12 13 14 15 16 17 18 19]
 [13 14 15 16 17 18 19 20]
 [14 15 16 17 18 19 20 21]
 [15 16 17 18 19 20 21 22]
 [16 17 18 19 20 21 22 23]
 [17 18 19 20 21 22 23 24]
 [18 19 20 21 22 23 24 25]]


In [8]:
arr1=np.array([[10,20,30],[40,50,60]])
print(arr1)
arr2=np.array([2,2,2])
print(arr2)
arr=arr1+arr2
print(arr)

[[10 20 30]
 [40 50 60]]
[2 2 2]
[[12 22 32]
 [42 52 62]]


In [9]:
arr1=np.array([[10,20],[30,40],[50,60]])
print(arr1)
arr2=np.array([2,2,2])
print(arr2)
arr=arr1+arr2
print(arr)

[[10 20]
 [30 40]
 [50 60]]
[2 2 2]


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [13]:
#copy vs view
#copy
arr=no.array([1,2,3,4])
print(arr)
arr_co=arr.copy
print(arr_co)
arr_co[0]=100
print(arr_co)
print(arr)

NameError: name 'no' is not defined