In [5]:
import numpy as np

In [6]:
#Join two array
arr1=np.array([1,2,3,4])
print(arr1)
arr2=np.array([5,6,7,8])
print(arr2)
print()
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4]
[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [7]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7]


In [10]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[6,7,8,9,10]])
print(arr1)
print(arr2)
print()
arr_new=np.concatenate((arr1,arr2),axis=0)
print(arr_new)
arr_new1=np.concatenate((arr1,arr2),axis=1)
print(arr_new1)

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [13]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[6,7,8,9]])
print(arr1)
print(arr2)
print()
arr_new=np.concatenate((arr1,arr2),axis=1)
print(arr_new)

[[1 2 3 4 5]]
[[6 7 8 9]]

[[1 2 3 4 5 6 7 8 9]]


In [14]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[6,7,8,9]])
print(arr1)
print(arr2)
print()
arr_new=np.concatenate((arr1,arr2),axis=0)
print(arr_new)

[[1 2 3 4 5]]
[[6 7 8 9]]



ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

In [16]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)
print()
arr_new=np.concatenate((arr1,arr2),axis=1)
print(arr_new)

[[1 2 3 4 5]]
[ 6  7  8  9 10]



ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [24]:
#stack
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)
print()
arr_new=np.stack((arr1,arr2))
print(arr_new)

[1 2 3 4 5]
[ 6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:
#stack
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)
print()
arr_new=np.stack((arr1,arr2),axis=1)
print(arr_new)

[1 2 3 4 5]
[ 6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)
print()
arr_new=np.stack((arr1,arr2),axis=0)
print(arr_new)

[1 2 3 4 5]
[ 6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [30]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)
print()
arr_new=np.stack((arr1,arr2))
print(arr_new)
arr_new_v=np.vstack((arr1,arr2))
print(arr_new_v)
arr_new_h=np.hstack((arr1,arr2))
print(arr_new_h)
arr_new_d=np.stack((arr1,arr2))
print(arr_new_d)

[1 2 3 4 5]
[ 6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [33]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[6,7,8,9,10]])
print(arr1)
print(arr2)
print()
arr_new=np.stack((arr1,arr2))
print(arr_new)
print()
arr_new_v=np.vstack((arr1,arr2))
print(arr_new_v)
arr_new_h=np.hstack((arr1,arr2))
print(arr_new_h)
arr_new_d=np.dstack((arr1,arr2))
print(arr_new_d)

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [35]:
arr=np.array([[10,20,30,40],[1,2,3,4,]])
arr1=np.append(arr,[[10,20,30,40],[10,30,40,50]],axis=0)
print(arr1)

[[10 20 30 40]
 [ 1  2  3  4]
 [10 20 30 40]
 [10 30 40 50]]


In [36]:
arr=np.array([[10,20,30,40],[1,2,3,4,]])
arr1=np.append(arr,[[10,20,30,40],[10,30,40,50]],axis=1)
print(arr1)

[[10 20 30 40 10 20 30 40]
 [ 1  2  3  4 10 30 40 50]]


In [38]:
arr=np.array([[10,20,30,40],[1,2,3,4,]])
arr1=np.append(arr,[[10,20,30,40],[10,30,40,50]],axis=2)
print(arr1)

AxisError: axis 2 is out of bounds for array of dimension 2

In [1]:
import numpy as np

In [4]:
arr1=np.array([10,20,30,40])
print(arr1)
arr2=np.array([100,200])
print(arr2)
arr_new=np.append(arr1,arr2,axis=0)
print(arr_new)

[10 20 30 40]
[100 200]
[ 10  20  30  40 100 200]


In [ ]:
arr1=np.array([10,20,30,40])
print(arr1)
arr_new=np.append(arr1,arr2,axis=0)


In [ ]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[100,200,300]])