In [5]:
import numpy as np

In [6]:
#Join two array
arr1=np.array([1,2,3,4])
print(arr1)
arr2=np.array([5,6,7,8])
print(arr2)
print()
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4]
[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [7]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7]


In [ ]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)
arr_new=np.concatenate((arr1,arr2),axis=0)
print(arr_new)
arr_new=np.concatenate((arr1,arr2),axis=0)

